server:
  port: 8081
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: service-edu
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456

  # 时间格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # spring cloud nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:com/qin/eduservice/mapper/xml/*.xml

#开启熔断机制
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    polling-interval-ms: 6000