#服务端口
server:
  port: 8082
  #服务名
spring:
  application:
    name: service-oss

  #环境设置：dev、test、prod
  profiles:
    active: dev

  #阿里云 OSS
  #不同的服务器，地址不同
aliyun:
  oss:
    file:
      endpoint: <endpoint>
      keyid: <keyid>
      keysecret: <keysecret>
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: <bucketname>
